### PR TITLE
Update to reset the ColorPalette in ST terminal Bug #115

### PR DESCRIPTION
**Pull request by wimstockman**
Hi Markus,
This is a solution for the problem I had with the ST terminal not resetting on exit.
Kind Regards
Wim

### CODE REVIEW

**Comment by gansm** [comment]
Hi Wim, it seems that we both approached at the same time on the same problem (b291d04). Initially, I had considered resetting all terminal settings, similar to Mintty. After learning that the st terminal can reset individual colors, I gave up on the reset solution.

**Comment by wimstockman** [comment]
Hi , I patched my version of ST terminal.
Seems there was only one line of code missing :-).
And sent my patch to the suckless group. maybe the will implement it. I keep you posted.
See ya

**Comment by gansm** [comment]
Hi Wim, the bad thing is that this capability is stored in the terminfo descriptions for "st-256color".

```bash
$ infocmp -1 st-256color | grep "oc=" | sed -e 's/,$//'
	oc=\E]104\007,
```

So the following should have worked:

```bash
$ for c in $(seq 1 7); do echo -ne "\033]4;${c};rgb:30/30/30\a\033[$((40 + c))m  "; done; echo -e "\n\033[mBe colorful"; tput oc
```

- - - - - - - - - -

I also saw that the keys &lt;Home&gt;, &lt;End&gt;, &lt;Pg Up&gt;, and &lt;Pg Dn&gt; send identical escape sequences as &lt;A1&gt; (Upper left of keypad), &lt;C1&gt; (Lower left of keypad), &lt;A3&gt; (Upper right of keypad), and &lt;C3&gt; (Lower right of keypad). That's awful because the keypad keys are in front of the other keys in the list. Therefore, these keys are wrongly detected. You can see this well with the program 'examples/keyboard'.


The keypad arrangement:

```
 ┌─────┬──────┬───────┐
 │ A1  │  up  │  A3   │
 ├─────┼──────┼───────┤
 │left │  B2  │ right │
 ├─────┼──────┼───────┤
 │ C1  │ down │  C3   │
 └─────┴──────┴───────┘
```

I am looking for a suitable solution here.

**Comment by wimstockman** [comment]
Hi Markus,
tested your keyboard example with : xterm, urxvt, termite , st.
There is only one and that is urxvt whom makes a difference between the Upper-left,Upper-right,Lower-right,Lower-left,Home,End,PgUp,PgDn
xterm and termite , just make it Home,End, PgUp, Pg Dn.
st makes it Upper-left,Upper-right,Lower-right,left but no home end pgdown or pgup.
weird :-)

Don't think so many people use ST. So you don't have to spent the weekend over it.
Kind regards,
Wim

**Comment by gansm** [comment]
I could fix the problem (5cb3ac3)

**Pull request closed without merging**
